export const UPDATE_TITLE = 'update_title'
export const UPDATE_EXCERPT = 'update_excerpt'
export const UPDATE_CONTENT ='update_content'
export const UPDATE_AUTHOR ='update_author'
export const ADD_POST ='add_post'